#!/bin/bash
# Configuração do Ambiente

# Configurar apache
sudo cp git.conf.sample /etc/apache2/mods-enabled/git.conf
sudo service apache2 restart

# Criar pastas
sudo -u www-data mkdir /var/www/.composer > /dev/null 2>&1
sudo -u www-data mkdir /var/www/tmp
sudo -u www-data mkdir /var/www/git
sudo -u www-data mkdir /var/www/apps
sudo -u www-data mkdir /var/www/apps/integracao

# Criar link simbolico da pasta publica do laravel para www/html/integracao
sudo -u www-data ln -s /var/www/apps/integracao/public /var/www/html/integracao

# Criar repositorio
sudo -u www-data git init --bare --shared /var/www/git/integracao.git

# Adicionar Hook
sudo -u www-data cp post-receive.linux.sample /var/www/git/integracao.git/hooks/post-receive
sudo -u www-data chmod 777 /var/www/git/integracao.git/hooks/*
